# Generated by Django 6.0.4 on 2026-05-02 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='gyms.gym'),
        ),
    ]
