# Generated by Django 6.0.4 on 2026-05-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_alter_favourite_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gym',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gym',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
