# Generated by Django 6.0.4 on 2026-05-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_gym_google_place_id_gym_latitude_gym_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='google_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='gym',
            name='opening_hours_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gym',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
