# Generated by Django 6.0.4 on 2026-05-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_gym_google_rating_gym_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
