# Generated by Django 6.0.4 on 2026-05-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_amenity_icon_created_at_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='image',
            field=models.FileField(blank=True, upload_to='gym_images/'),
        ),
    ]
