# Generated by Django 6.0.4 on 2026-05-02 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def approve_existing_gyms(apps, schema_editor):
    Gym = apps.get_model('gyms', 'Gym')
    Gym.objects.filter(status='pending').update(
        status='approved',
        approved_at=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0010_alter_review_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_gyms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gym',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.RunPython(approve_existing_gyms, migrations.RunPython.noop),
    ]
